# Generated by Django 4.2.10 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cancelled',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='dispatch_after',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
